spring.application.name=activity-service

spring.mongodb.uri=mongodb+srv://surajjha:surajjha@cluster0.idxftnd.mongodb.net/?appName=Cluster0
spring.mongodb.database=fitnessactivity

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

server.port=8082
