spring.application.name=userservice

spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_user_db
spring.datasource.username=surajjha
spring.datasource.password=surajjha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8081