spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_user_db
spring.datasource.username=surajjha
spring.datasource.password=surajjha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

server.port=8081